### ISSUE TITLE
Implement a CD pipeline

### ISSUE THREAD

**Issue by wanLo** [studieren-ohne-grenzen/website#5]
We want the website to be easily editable also for people without direct server access. Since we already have a working gitea integration, we could build on it. The idea is that people log into gitea with their SOG credentials and if they belong to a certain group within gitea (editors, moderators, ...) they should be able to edit the staging branch and / or push to master. We use a webhook from within gitea to automate deployment to `kueken.` and the public version (linked to master). Only content (images, json and md files) is stored on gitea, while everything technical stays on github. This should also keep the gitea repository clutter free. An open question is how warnings and or errors that occur on deployment (while generating the static page) can be dealt with.

**Comment by glatteis** [comment]
Done :) the content repository is https://github.com/studieren-ohne-grenzen/website-content
